# voir "https://docs.travis-ci.com/user/customizing-the-build/"
#      "https://docs.travis-ci.com/user/languages/python"
#      "https://github.com/getsentry/sentry/blob/master/.travis.yml"
#      "https://github.com/jpvanhal/flask-split/blob/master/.travis.yml"

# Pour plus d'infos relativement a la construction du document

# 1- language du projet
#   ex : language: python
language: python

# 2- version du language
#   note : la version par defaut de python est 2.7
python:
- 2.6
- 2.7
- 3.4
- pypy

env:
- DJANGO_VERSION=1.9.6

#a executer avant l'installation
before_install:
- pyclean .
- sudo pip install virtualenv
- virtualenv py_env
- sudo py_env/bin/pip install --upgrade setuptools
- sudo py_env/bin/pip install zc.buildout
   
# 4- install addons
# install: ./[Script a executer]
install:
- sudo py_env/bin/pip install coveralls
- sudo py_env/bin/buildout
- cd project
- cp conf.py.edit conf.py
- cd ..
- bin/django makemigrations
- bin/django migrate --fake-initial

# 5- script de test
# script: [quoi executer]
#   ex: script: nosetests
#   ex2: script: make test
# note: si script est absent du fichier => message d'erreur + fail du build
script:
- py_env/bin/coverage run bin/django test

after_success:
- py_env/bin/coveralls
